MIN_ANIMAL_ENERGY = 20
MAX_ANIMAL_ENERGY = 100

COLD_BLOODED_OPTIMAL_TEMPERATURE = [15, 20]
COLD_BLOODED_TEMPERATURE_SENSIBILITY = 0.5

WARM_BLOODED_OPTIMAL_TEMPERATURE = [5, 30]
WARM_BLOODED_TEMPERATURE_SENSIBILITY  = 0.1
