FIELD_WIDTH = 150
FIELD_HEIGHT = 100
START_ANIMAL_NUMBER = 200
START_ANIMAL_RATIO = [50, 50]  # пропорция хладнокровных/теплокровных в %

BASE_CELL_TEMPERATURE = 20
CORPSE_DECAY_TIME = 5
MAX_CORPSE_ENERGY = 50
MAX_PLANTS_NUTRITION = 30